name: 🐛 Сообщить о баге
about: Опишите, как воспроизвести ошибку
title: ''
labels: bug
assignees: ''

body:
  - type: textarea
    id: description
    attributes:
      label: Описание
      placeholder: Опишите, что пошло не так
      value: |
        ## Что произошло
        <!-- Вставьте сюда описание -->

        ## Как воспроизвести
        1. Открыть приложение
        2. Ввести ...
        3. Нажать ...
        4. Наблюдать ошибку

        ## Ожидаемое поведение
        <!-- Что должно было произойти -->

    validations:
      required: true

  - type: input
    id: os
    attributes:
      label: Операционная система
      placeholder: Windows 11, Ubuntu 24.04, macOS Sonoma
    validations:
      required: true

  - type: input
    id: python-version
    attributes:
      label: Версия Python (если запускаете из исходников)
      placeholder: 3.13.2
    validations:
      required: false